import { Activity, Stethoscope, Heart, Brain, Thermometer, Pill } from "lucide-react";

export const SYMPTOM_CATEGORIES = {
  respiratory: {
    name: "Respiratory",
    icon: Activity,
    color: "text-blue-500",
    bgColor: "bg-blue-50",
    symptoms: [
      "Cough",
      "Shortness of breath",
      "Wheezing",
      "Chest congestion",
      "Runny nose",
      "Sore throat",
      "Sneezing",
      "Difficulty breathing",
    ],
  },
  gastrointestinal: {
    name: "Gastrointestinal",
    icon: Pill,
    color: "text-green-500",
    bgColor: "bg-green-50",
    symptoms: [
      "Nausea",
      "Vomiting",
      "Diarrhea",
      "Constipation",
      "Stomach pain",
      "Bloating",
      "Loss of appetite",
      "Heartburn",
    ],
  },
  cardiac: {
    name: "Cardiac",
    icon: Heart,
    color: "text-red-500",
    bgColor: "bg-red-50",
    symptoms: [
      "Chest pain",
      "Rapid heartbeat",
      "Irregular heartbeat",
      "Dizziness",
      "Shortness of breath during activity",
      "Swelling in legs",
      "Fatigue",
    ],
  },
  neurological: {
    name: "Neurological",
    icon: Brain,
    color: "text-purple-500",
    bgColor: "bg-purple-50",
    symptoms: [
      "Headache",
      "Migraine",
      "Dizziness",
      "Confusion",
      "Memory problems",
      "Numbness",
      "Tingling",
      "Vision changes",
      "Difficulty speaking",
    ],
  },
  general: {
    name: "General Health",
    icon: Thermometer,
    color: "text-amber-500",
    bgColor: "bg-amber-50",
    symptoms: [
      "Fever",
      "Fatigue",
      "Body aches",
      "Chills",
      "Night sweats",
      "Unexplained weight loss",
      "Weakness",
      "Malaise",
    ],
  },
  musculoskeletal: {
    name: "Musculoskeletal",
    icon: Stethoscope,
    color: "text-teal-500",
    bgColor: "bg-teal-50",
    symptoms: [
      "Joint pain",
      "Muscle pain",
      "Back pain",
      "Stiffness",
      "Swelling in joints",
      "Limited range of motion",
      "Muscle weakness",
    ],
  },
};

export const HOME_REMEDIES = {
  cold: [
    "Rest and sleep plenty",
    "Stay hydrated with water, tea, and clear broths",
    "Use a humidifier to ease congestion",
    "Gargle with warm salt water for sore throat",
    "Honey and lemon in warm water can soothe symptoms",
  ],
  fever: [
    "Rest and stay hydrated",
    "Take over-the-counter fever reducers (acetaminophen or ibuprofen)",
    "Apply cool, damp cloths to forehead",
    "Take a lukewarm bath",
    "Wear light clothing and use light bedding",
  ],
  headache: [
    "Rest in a quiet, dark room",
    "Apply a cold or warm compress to forehead",
    "Stay hydrated",
    "Try relaxation techniques",
    "Over-the-counter pain relievers may help",
  ],
  stomachache: [
    "Rest your stomach by eating bland foods",
    "Stay hydrated with small sips of water",
    "Try ginger tea or peppermint tea",
    "Avoid fatty, spicy, or acidic foods",
    "Apply a warm compress to abdomen",
  ],
};

export const URGENCY_LEVELS = {
  emergency: {
    title: "Emergency",
    description: "Seek immediate medical attention",
    color: "destructive",
    bgClass: "bg-gradient-emergency",
    textClass: "text-destructive-foreground",
  },
  urgent: {
    title: "Urgent",
    description: "See a doctor within 24 hours",
    color: "urgent",
    bgClass: "bg-gradient-urgent",
    textClass: "text-urgent-foreground",
  },
  routine: {
    title: "Routine",
    description: "Schedule a regular appointment",
    color: "success",
    bgClass: "bg-success",
    textClass: "text-success-foreground",
  },
};
